<?php

/*
 * Remove default product archive title + description
 */
remove_action( 'woocommerce_before_main_content', 'woocommerce_breadcrumb', 20 );
remove_action( 'woocommerce_archive_description', 'woocommerce_taxonomy_archive_description', 10 );
remove_action( 'woocommerce_archive_description', 'woocommerce_product_archive_description', 10 );
remove_action( 'woocommerce_shop_loop_header', 'woocommerce_product_taxonomy_archive_header', 10 );
add_filter( 'woocommerce_show_page_title', '__return_false' );


/*
 * Remove all inline-styles from images generated by WP
 */
add_filter( 'wp_img_tag_add_auto_sizes', '__return_false' );
